export const MOCK_ISSUES = [
  {
    id: '101',
    title: 'Tarihi Yarımada Kaldırım ve Yol Göçmesi',
    category: 'TRANSPORTATION',
    priority: 'HIGH',
    status: 'OPEN',
    city: 'İstanbul',
    district: 'Fatih',
    address: 'Alemdar, Divan Yolu Cd. No:1, 34110 Fatih/İstanbul',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    latitude: 41.0082,
    longitude: 28.9784,
    upvoteCount: 42,
  },
  {
    id: '102',
    title: 'Moda Sahili Yoğun Çöp ve Koku Şikayeti',
    category: 'ENVIRONMENT',
    priority: 'MEDIUM',
    status: 'IN_REVIEW',
    city: 'İstanbul',
    district: 'Kadıköy',
    address: 'Caferağa, Moda Sahili, 34710 Kadıköy/İstanbul',
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    latitude: 40.9788,
    longitude: 29.0255,
    upvoteCount: 156,
  },
  {
    id: '103',
    title: 'Barbaros Bulvarı Ana Su Borusu Patlağı',
    category: 'WATER_SANITATION',
    priority: 'CRITICAL',
    status: 'OPEN',
    city: 'İstanbul',
    district: 'Beşiktaş',
    address: 'Cihannüma, Barbaros Blv., 34353 Beşiktaş/İstanbul',
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    latitude: 41.0422,
    longitude: 29.0067,
    upvoteCount: 89,
  },
  {
    id: '104',
    title: 'Salacak Sahil Yolu Aydınlatma Arızası',
    category: 'LIGHTING',
    priority: 'LOW',
    status: 'OPEN',
    city: 'İstanbul',
    district: 'Üsküdar',
    address: 'Salacak, Salacak İskele Sk., 34668 Üsküdar/İstanbul',
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    latitude: 41.0256,
    longitude: 29.0112,
    upvoteCount: 12,
  },
  {
    id: '105',
    title: 'Mecidiyeköy Meydanı Trafik Lambası Arızası',
    category: 'INFRASTRUCTURE',
    priority: 'HIGH',
    status: 'RESOLVED',
    city: 'İstanbul',
    district: 'Şişli',
    address: 'Fulya, Büyükdere Cd., 34394 Şişli/İstanbul',
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    latitude: 41.0664,
    longitude: 28.9922,
    upvoteCount: 204,
  },
  {
    id: '106',
    title: 'Belgrad Ormanı Girişi Yasadışı Moloz Dökümü',
    category: 'ENVIRONMENT',
    priority: 'HIGH',
    status: 'OPEN',
    city: 'İstanbul',
    district: 'Sarıyer',
    address: 'Bahçeköy Merkez, Orman Yolu, 34473 Sarıyer/İstanbul',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    latitude: 41.1687,
    longitude: 28.9789,
    upvoteCount: 67,
  },
  {
    id: '107',
    title: 'İstiklal Caddesi Rögar Kapağı Çökmesi',
    category: 'INFRASTRUCTURE',
    priority: 'CRITICAL',
    status: 'IN_REVIEW',
    city: 'İstanbul',
    district: 'Beyoğlu',
    address: 'Hüseyinağa, İstiklal Cd., 34435 Beyoğlu/İstanbul',
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    latitude: 41.0340,
    longitude: 28.9778,
    upvoteCount: 112,
  },
  {
    id: '108',
    title: 'İncirli Caddesi Fiber Optik Kablo Kazısı Çukuru',
    category: 'INFRASTRUCTURE',
    priority: 'MEDIUM',
    status: 'RESOLVED',
    city: 'İstanbul',
    district: 'Bakırköy',
    address: 'Zuhuratbaba, İncirli Cd., 34147 Bakırköy/İstanbul',
    createdAt: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    latitude: 40.9902,
    longitude: 28.8741,
    upvoteCount: 34,
  },
  {
    id: '109',
    title: 'Tepeüstü Mahallesi Başıboş Köpek Sürüsü',
    category: 'SECURITY',
    priority: 'HIGH',
    status: 'OPEN',
    city: 'İstanbul',
    district: 'Ümraniye',
    address: 'Tepeüstü, Alemdağ Cd., 34771 Ümraniye/İstanbul',
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    latitude: 41.0211,
    longitude: 29.1362,
    upvoteCount: 231,
  },
  {
    id: '110',
    title: 'Maltepe Sahil Yolu Bisiklet Yolu İşgali',
    category: 'TRANSPORTATION',
    priority: 'LOW',
    status: 'IN_REVIEW',
    city: 'İstanbul',
    district: 'Maltepe',
    address: 'Yalı, Turgut Özal Blv., 34844 Maltepe/İstanbul',
    createdAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    latitude: 40.9234,
    longitude: 29.1311,
    upvoteCount: 88,
  },
  {
    id: '111',
    title: 'E-5 Yanyol Asfalt Çatlakları ve Çukurlar',
    category: 'TRANSPORTATION',
    priority: 'HIGH',
    status: 'OPEN',
    city: 'İstanbul',
    district: 'Pendik',
    address: 'Doğu, E-5 Yanyol, 34890 Pendik/İstanbul',
    createdAt: new Date(Date.now() - 9 * 60 * 60 * 1000).toISOString(),
    latitude: 40.8789,
    longitude: 29.2312,
    upvoteCount: 145,
  },
  {
    id: '112',
    title: 'Çam ve Sakura Hastanesi Yolu Su Baskını',
    category: 'WATER_SANITATION',
    priority: 'CRITICAL',
    status: 'OPEN',
    city: 'İstanbul',
    district: 'Başakşehir',
    address: 'Başakşehir, Olimpiyat Blv., 34480 Başakşehir/İstanbul',
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    latitude: 41.1072,
    longitude: 28.7981,
    upvoteCount: 380,
  },
  {
    id: '113',
    title: 'Avrasya Tüneli Çıkışı Bariyer Hasarı',
    category: 'INFRASTRUCTURE',
    priority: 'MEDIUM',
    status: 'RESOLVED',
    city: 'İstanbul',
    district: 'Zeytinburnu',
    address: 'Kazlıçeşme, Kennedy Cd., 34020 Zeytinburnu/İstanbul',
    createdAt: new Date(Date.now() - 96 * 60 * 60 * 1000).toISOString(),
    latitude: 40.9856,
    longitude: 28.9167,
    upvoteCount: 56,
  },
  {
    id: '114',
    title: 'Yakacık Tepesi Orman Yangını Şüphesi',
    category: 'ENVIRONMENT',
    priority: 'CRITICAL',
    status: 'IN_REVIEW',
    city: 'İstanbul',
    district: 'Kartal',
    address: 'Yakacık Çarşı, Kartal Orman Yolu, 34876 Kartal/İstanbul',
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    latitude: 40.9221,
    longitude: 29.2155,
    upvoteCount: 512,
  },
  {
    id: '115',
    title: 'Finans Merkezi İnşaat Tozu ve Gürültü Kirliliği',
    category: 'ENVIRONMENT',
    priority: 'MEDIUM',
    status: 'OPEN',
    city: 'İstanbul',
    district: 'Ataşehir',
    address: 'Barbaros, Gelincik Sk., 34746 Ataşehir/İstanbul',
    createdAt: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
    latitude: 41.0049,
    longitude: 29.1021,
    upvoteCount: 289,
  },
  {
    id: '116',
    title: 'Kızılay Meydanı Yaya Geçidi Çizgilerinin Silinmesi',
    category: 'TRANSPORTATION',
    priority: 'MEDIUM',
    status: 'IN_REVIEW',
    city: 'Ankara',
    district: 'Çankaya',
    address: 'Kızılay, Atatürk Blv, 06420 Çankaya/Ankara',
    createdAt: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
    latitude: 39.9208,
    longitude: 32.8541,
    upvoteCount: 125,
  },
  {
    id: '117',
    title: 'Tunalı Hilmi Caddesi Çöp Konteyneri Yetersizliği',
    category: 'ENVIRONMENT',
    priority: 'LOW',
    status: 'OPEN',
    city: 'Ankara',
    district: 'Çankaya',
    address: 'Kavaklıdere, Tunalı Hilmi Cd., 06680 Çankaya/Ankara',
    createdAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    latitude: 39.9048,
    longitude: 32.8615,
    upvoteCount: 65,
  },
  {
    id: '118',
    title: 'Keçiören Metro İstasyonu Yürüyen Merdiven Arızası',
    category: 'INFRASTRUCTURE',
    priority: 'HIGH',
    status: 'OPEN',
    city: 'Ankara',
    district: 'Keçiören',
    address: 'Şefkat, Cumhuriyet Cd., 06300 Keçiören/Ankara',
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    latitude: 39.9806,
    longitude: 32.8697,
    upvoteCount: 180,
  },
  {
    id: '119',
    title: 'Yenimahalle Demetevler Parkı Aydınlatma Eksikliği',
    category: 'LIGHTING',
    priority: 'MEDIUM',
    status: 'RESOLVED',
    city: 'Ankara',
    district: 'Yenimahalle',
    address: 'Demetevler, 408. Cd., 06200 Yenimahalle/Ankara',
    createdAt: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    latitude: 39.9678,
    longitude: 32.8105,
    upvoteCount: 42,
  },
  {
    id: '120',
    title: 'Alsancak Kordon Sahil Yolu Taş Çökmesi',
    category: 'TRANSPORTATION',
    priority: 'HIGH',
    status: 'OPEN',
    city: 'İzmir',
    district: 'Konak',
    address: 'Alsancak, Kordonboyu, 35220 Konak/İzmir',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    latitude: 38.4361,
    longitude: 27.1418,
    upvoteCount: 310,
  },
  {
    id: '121',
    title: 'Karşıyaka Çarşı Girişi Rögar Kapağı Taşması',
    category: 'WATER_SANITATION',
    priority: 'CRITICAL',
    status: 'IN_REVIEW',
    city: 'İzmir',
    district: 'Karşıyaka',
    address: 'Donmacı, Kemalpaşa Cd., 35580 Karşıyaka/İzmir',
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    latitude: 38.4552,
    longitude: 27.1147,
    upvoteCount: 220,
  },
  {
    id: '122',
    title: 'Bornova Küçükpark Çevresi Gürültü Kirliliği',
    category: 'ENVIRONMENT',
    priority: 'LOW',
    status: 'OPEN',
    city: 'İzmir',
    district: 'Bornova',
    address: 'Kazımdirik, Küçükpark, 35100 Bornova/İzmir',
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    latitude: 38.4619,
    longitude: 27.2185,
    upvoteCount: 95,
  },
  {
    id: '123',
    title: 'Buca Şirinyer Metro Durağı Yaya Üst Geçit Hasarı',
    category: 'SECURITY',
    priority: 'HIGH',
    status: 'RESOLVED',
    city: 'İzmir',
    district: 'Buca',
    address: 'Şirinyer, Aydın Hatboyu Cd., 35380 Buca/İzmir',
    createdAt: new Date(Date.now() - 120 * 60 * 60 * 1000).toISOString(),
    latitude: 38.3892,
    longitude: 27.1517,
    upvoteCount: 47,
  },
  {
    id: '124',
    title: 'Nilüfer FSM Bulvarı Orta Refüj Sulama Hortumu Patlağı',
    category: 'PARKS',
    priority: 'MEDIUM',
    status: 'OPEN',
    city: 'Bursa',
    district: 'Nilüfer',
    address: 'İhsaniye, FSM Blv., 16130 Nilüfer/Bursa',
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    latitude: 40.2184,
    longitude: 28.9567,
    upvoteCount: 88,
  },
  {
    id: '125',
    title: 'Osmangazi Kapalı Çarşı Yanı Trafo Tehlikesi',
    category: 'SECURITY',
    priority: 'CRITICAL',
    status: 'IN_REVIEW',
    city: 'Bursa',
    district: 'Osmangazi',
    address: 'Nalbantoğlu, Kapalı Çarşı, 16010 Osmangazi/Bursa',
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    latitude: 40.1837,
    longitude: 29.0601,
    upvoteCount: 154,
  },
  {
    id: '126',
    title: 'Yıldırım Şevket Yılmaz Hastane Yolu Asfalt Bozukluğu',
    category: 'TRANSPORTATION',
    priority: 'HIGH',
    status: 'OPEN',
    city: 'Bursa',
    district: 'Yıldırım',
    address: 'Mimar Sinan, Mimar Sinan Cd., 16310 Yıldırım/Bursa',
    createdAt: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
    latitude: 40.1895,
    longitude: 29.1172,
    upvoteCount: 102,
  },
  {
    id: '127',
    title: 'Muratpaşa Kaleiçi Restorasyon Atıkları',
    category: 'ENVIRONMENT',
    priority: 'LOW',
    status: 'RESOLVED',
    city: 'Antalya',
    district: 'Muratpaşa',
    address: 'Kılıçarslan, Kaleiçi, 07100 Muratpaşa/Antalya',
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    latitude: 36.8841,
    longitude: 30.7056,
    upvoteCount: 33,
  },
  {
    id: '128',
    title: 'Konyaaltı Akdeniz Bulvarı Bisiklet Yolu Çizgileri Silik',
    category: 'TRANSPORTATION',
    priority: 'MEDIUM',
    status: 'OPEN',
    city: 'Antalya',
    district: 'Konyaaltı',
    address: 'Arapsuyu, Akdeniz Blv., 07070 Konyaaltı/Antalya',
    createdAt: new Date(Date.now() - 15 * 60 * 60 * 1000).toISOString(),
    latitude: 36.8687,
    longitude: 30.6439,
    upvoteCount: 76,
  },
  {
    id: '129',
    title: 'Kepez Dokuma Park Girişi Başıboş Köpekler',
    category: 'SECURITY',
    priority: 'HIGH',
    status: 'IN_REVIEW',
    city: 'Antalya',
    district: 'Kepez',
    address: 'Fabrikalar, Namık Kemal Blv., 07090 Kepez/Antalya',
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    latitude: 36.9142,
    longitude: 30.6728,
    upvoteCount: 205,
  }
];export const MOCK_STATS = {
  total: MOCK_ISSUES.length,
  open: MOCK_ISSUES.filter(i => i.status === 'OPEN').length,
  inReview: MOCK_ISSUES.filter(i => i.status === 'IN_REVIEW').length,
  resolved: MOCK_ISSUES.filter(i => i.status === 'RESOLVED').length,
  thisMonth: MOCK_ISSUES.length,
  thisMonthChange: 24.5, // Örnek artış yüzdesi
};
